### PR TITLE
WIP : Forward Euler implementation using HHL

### PR DESCRIPTION
**Pull request by dgan181**
First implementation of the Forward Euler method using the existing HHL implementation.
(https://arxiv.org/abs/1010.2745).

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Super cool!
About your issues
> 1. When I try to run the test file, I am given an error saying that the functions haven't been defined. I have to run the file (`src\lin_diffEq_HHL.jl`) separately to get the test file to execute.

After excuting `git merge master`, I can run `test/lin_diffEq_HHL.jl` correctly.
Your issue may be related to using an older version master branch with an incorrect `Project.toml`. Try to merge the master branch first (sometimes, you need to reinstall related packages).

Also, the dependacy of `OrdinaryDiffEq` should be added to `Project.toml`. Otherwise the CI will fail. Is it possible to not using this package in Test? If it is nessesary, please add it in `Project.toml` by excuting the following commands in pkg mode in the top level folder
```
pkg> activate .
(QuAlgorithmZoo) pkg> add OrdinaryDiffEq
```

> 2. I am not sure how to input the input state as given in the paper. (Coupled to the states that represent time) 

(reading the paper, I will be back soon...)

**Comment by Roger-luo** [comment]
The older UUID was not compatible with METADATA. I've fixed it in a recent commit. 

If you want to use a package in test only, you should put it into [extra] and [target]. This will let the Pkg know this is test only dependency.

**Comment by dgan181** [comment]
@GiggleLiu I made the changes you asked me make. I still get the same error.

**Comment by Roger-luo** [comment]
I think the `Project.toml` configuration is fixed now. This is due to legacy configuration generated in 0.6 era. I've updated it to 1.0 version. 0.7 is dropped.

@dgan181 please notice that as the README says, this repo is currently a bit messy (its code base etc.) also the examples are all should be working, the interface might be a bit ugly. So feel free to tell us if there's anything you think can be improved during your own development.

**Pull request merged**
