### PR TITLE
Create VQE_H2_4bit.ipynb

### PR DESCRIPTION
**Pull request by EigenSolver**
add example for H2 under Jordan-Weigner  transformation with PyCall to OpenFermion

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Great, this PR is wonderful, thank you so much. Could you please also add some description in this README bout the notebook?

https://github.com/Neuromancer43/QuAlgorithmZoo.jl/blob/patch-1/examples/VQE/README.md

**Comment by Roger-luo** [comment]
This is nice PR! Could you convert this notebook to https://github.com/fredrikekre/Literate.jl format? so it'll be easier to review your PR. Thanks!

**Comment by EigenSolver** [comment]
Have convert the notebook to Literate.jl format :smiley: :

**Comment by GiggleLiu** [comment]
Good, :+1: . Don't forget to add some description in README, mainly about how to setup the environment and how to run the code, several lines should be good.
Thanks for your effort.

**Comment by GiggleLiu** [comment]
:tada:

**Pull request merged**
